### ISSUE TITLE
Track down John E Dell and ask permission to give a libre licence to this

### ISSUE THREAD

**Issue by oldpatientsea** [oldpatientsea/DRUG-WARS-for-the-Agon-Light#2]
This is open source but since John E Dell owns the copyright to the original, this is offered without licence.

**Comment by gammalogic** [comment]
Unfortunately I do not have any contacts for John Dell, although in a Wired article in 2021 he was stated as managing/operating a software consultancy company called Mutations Ltd. It would be nice to have his blessing, of course, and to be able to get the software released under a free licence.

I have been looking for the original source code to Drug Wars for a long time as I was looking to recreate it for the NES and Altair 8800. I prefer the original game to all the remakes (except yours, which I haven't played yet) and I've never been able to determine how closely the remakes were based on the original. My intention is to faithfully recreate the DOS version without guessing as to how it had been written. I had considered decompiling the DOS Basic executable but the binary will have a lot of BASIC compiler code in there that I don't understand. And (I think this is true for almost everyone) I have heard references made to the original TRS-80 version but maybe that's a lost relic now.

**Comment by oldpatientsea** [comment]
Thanks for the comment.
